/* UserActivity.cs
This files contains the UserActivity class, which is one of the utility models used by the ProjectManager web application.
Utility models are models that are differentialed from the regular models that are used to define database tables/schemes. Utility models
are used as containers of data within the server side application.

The UserActivity class is used by the ProjectActivity class to store generate project activity information in the ProjectManager web
application. This object is then used to sent activity information to the client-side 
*/

using System;
using System.ComponentModel.DataAnnotations;

namespace ProjectManager.Models.UtilityModels
{
    //represents a user activity generated by the ProjectActivity class
    public class UserActivity
    {
        //the id of the project where the activity is taking place
        [Required]
        public int ProjectId {get; set;}

        //the id of the task where the activity is taking place
        [Required]
        public int TaskId {get; set;}

        //the string that describes the activity
        [Required]
        public string Activity {get; set;}

        //the time of the activity
        [Required]
        public DateTime Time {get; set;}
    }
}